version: '3.8'
services:
  postgres:
    image: ${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ${GLOBAL_NETWORK:-labs}

  keycloak:
    depends_on:
      - postgres
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER_NAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: on-failure
    networks:
      - ${GLOBAL_NETWORK:-labs}