version: '3.8'
services:
  amq:
    container_name: ${AMQ_CONTAINER_NAME}
    image: ${AMQ_VERSION}
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
    environment:
      ACTIVEMQ_CONFIG_NAME: ${AMQ_HOSTNAME}
      ACTIVEMQ_LOGGER_LOGLEVEL: ${AMQ_LOG_LEVEL}
      ACTIVEMQ_CONFIG_PENDINGMESSAGELIMIT: ${AMQ_PENDING_MESSAGE_LIMIT}
      ACTIVEMQ_CONFIG_STORAGEUSAGE: ${AMQ_STORAGEUSAGE}
      ACTIVEMQ_CONFIG_MAXCONNECTION: ${AMQ_MAXCONNECTION}
      ACTIVEMQ_CONFIG_FRAMESIZE: ${AMQ_FRAMESIZE}
      ACTIVEMQ_CONFIG_SCHEDULERENABLED: ${AMQ_SCHEDULER_ENABLE}
      ACTIVEMQ_CONFIG_AUTHENABLED: ${AMQ_AUTH_ENABLED}
      ACTIVEMQ_CONFIG_MINMEMORY: ${AMQ_MIN_MEMORY}
      ACTIVEMQ_CONFIG_MAXMEMORY: ${AMQ_MAX_MEMORY}
      ACTIVEMQ_DEFAULTACCOUNT: ${AMQ_DEFAULT_ACCOUNT}
      ACTIVEMQ_ADMIN_LOGIN: ${AMQ_ADMIN_LOGIN}
      ACTIVEMQ_ADMIN_PASSWORD: ${AMQ_ADMIN_PASSWORD}
      ACTIVEMQ_USERS_admin: ${AMQ_USERS}
      ACTIVEMQ_GROUPS_admin: ${AMQ_GROUPS}
      ACTIVEMQ_JMX_admin_ROLE: ${AMQ_JMX_ROLE_RW}.
      ACTIVEMQ_JMX_admin_PASSWORD: ${AMQ_JMX_PASS}
      ACTIVEMQ_CONFIG_TOPICS_TOPIC1: ${AMQ_TOPIC}
      ACTIVEMQ_CONFIG_QUEUES_LABS: ${AMQ_QUEUE_LAB}
    volumes:
      - ./data/activemq:/data
      - ./log/activemq:/var/log/activemq
    restart: always
    networks:
      - ${GLOBAL_NETWORK:-labs}
